services:
    # Legacy kernel
    cvuorinen_legacy.legacy_kernel:
        class: Cvuorinen\LegacyBundle\Kernel\LegacyKernel
        arguments: [%legacy.site_index%, @service_container]

    # Event listeners
    cvuorinen_legacy.listener.legacy_kernel_listener:
        class: Cvuorinen\LegacyBundle\EventListener\LegacyKernelListener
        arguments: [@cvuorinen_legacy.legacy_kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    # User provider (for authenticator)
    cvuorinen_legacy.user_provicer:
        class: Cvuorinen\LegacyBundle\Security\LegacyUserProvider

    # Authenticator
    cvuorinen_legacy.legacy_authenticator:
        class:     Cvuorinen\LegacyBundle\Security\LegacyAuthenticator
        arguments: ["@cvuorinen_legacy.user_provicer"]