<?php

namespace Cvuorinen\LegacyBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class LegacyController extends Controller
{
    /**
     * @Route("/{filename}.php", name="_legacy")
     */
    public function legacyAction(Request $request, $filename)
    {
        $legacyAppPath = $this->container->getParameter('legacy.path');

        if (! file_exists($legacyAppPath)) {
            throw new \RuntimeException(
                sprintf('Invalid legacy app path (%s), unable to handle request', $legacyAppPath));
        }

        $filePath = $legacyAppPath . $filename . '.php';

        if (! file_exists($filePath)) {
            throw $this->createNotFoundException();
        }

        // Assign Container to a local variable so it can be used in legacy app
        $container = $this->container;
        // Request is already in a local variable $request

        // Start output buffering to capture output generated by the legacy app
        ob_start();

        // Change current working dir to legacy base dir for relative includes etc. in the legacy app
        chdir($legacyAppPath);

        require_once $filePath;

        $legacyOutput = ob_get_clean();
        $response = new Response($legacyOutput);

        return $response;
    }

    /**
     * @Route("/{filename}.html", name="_legacy_example")
     */
    public function legacyMenuAction(Request $request)
    {
        $legacyKernel = $this->container->get('cvuorinen_legacy.legacy_kernel');

        return $legacyKernel->handle($request);
    }
}
