<?php

namespace Cvuorinen\LegacyBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class LegacyController extends Controller
{
    /**
     * @Route("/{filename}.php", name="_legacy")
     */
    public function legacyAction($filename)
    {
        $legacyAppPath = $this->container->getParameter('legacy.path');

        if (! file_exists($legacyAppPath)) {
            throw new \RuntimeException(
                sprintf('Invalid legacy app path (%s), unable to handle request', $legacyAppPath));
        }

        $filePath = $legacyAppPath . $filename . '.php';

        if (! file_exists($filePath)) {
            throw $this->createNotFoundException();
        }

        // Start output buffering to capture output generated by the legacy app
        ob_start();

        // Change current working dir to legacy base dir for relative includes etc. in the legacy app
        chdir($legacyAppPath);

        require_once $filePath;

        $legacyOutput = ob_get_clean();
        $response = new Response($legacyOutput);

        return $response;
    }
}
